###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

FROM alpine:3.17

RUN mkdir import

RUN chown -R 1000:3000 /import
USER 1000:3000

COPY import/keycloak-themes/ import/themes
COPY import/realm-config/consortia/catenax-central/dev/ import/catenax-central/dev/realms
COPY import/realm-config/consortia/catenax-shared/dev/ import/catenax-shared/dev/realms
COPY import/realm-config/consortia/catenax-central/int/ import/catenax-central/int/realms
COPY import/realm-config/consortia/catenax-shared/int/ import/catenax-shared/int/realms
COPY import/realm-config/consortia/catenax-central/beta/ import/catenax-central/beta/realms
COPY import/realm-config/consortia/catenax-shared/beta/ import/catenax-shared/beta/realms
COPY import/realm-config/consortia/catenax-central/pen/ import/catenax-central/pen/realms
COPY import/realm-config/consortia/catenax-shared/pen/ import/catenax-shared/pen/realms
COPY import/realm-config/consortia/catenax-central/rc/ import/catenax-central/rc/realms
COPY import/realm-config/consortia/catenax-shared/rc/ import/catenax-shared/rc/realms
COPY import/realm-config/consortia/catenax-central/stable/ import/catenax-central/stable/realms
COPY import/realm-config/consortia/catenax-shared/stable/ import/catenax-shared/stable/realms
COPY import/realm-config/consortia/catenax-central/upgrade/ import/catenax-central/upgrade/realms
COPY import/realm-config/consortia/catenax-shared/upgrade/ import/catenax-shared/upgrade/realms
