{{- if and (eq .Values.instanceType "central" ) .Values.seeding.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.seeding.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "batch.kubernetes.io/job-tracking": "true"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"  
spec:
  template:
    metadata:
      name: {{ .Values.seeding.name }}  
    spec:
      restartPolicy: Never
      containers:
        - name: echo-container
          image: busybox
          command: ["/bin/sh", "-c", "echo 'This is the seeding job only for Central instances!'"]
{{- end }}
